[package]
name = "bevy_mario_clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_fly_camera = "0.8.0"
bevy_rapier2d = "0.12.1"
bevy-ui-navigation = "0.13.1"
